Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.vm.network "forwarded_port", guest: 2375, host: 2375
    config.vm.provision "shell", path: "provisioner.sh"
end
